"""Your migration message

Revision ID: 19054ab9137d
Revises: f9f05c7ee241
Create Date: 2024-01-12 18:56:47.295279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19054ab9137d'
down_revision = 'f9f05c7ee241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
