"""Your migration message

Revision ID: f9f05c7ee241
Revises: da35890f0fcb
Create Date: 2024-01-12 18:50:22.681402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f05c7ee241'
down_revision = 'da35890f0fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kart', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
